### ISSUE TITLE
Unable to generate site - KeyError: 'filenames'`

### ISSUE THREAD

**Issue by nickperkins** [MinchinWeb/minchin.pelican.plugins.image_process#5]
I'm unable to generate images using the standard configuration as per the README. 

Output from debug:

(nicholasperkins.com) ➜  nicholasperkins.com git:(master) ✗ pelican --debug
DEBUG: Pelican version: 4.1.0
DEBUG: Python version: 3.7.3
WARNING: Locale could not be set. Check the LOCALE setting, ensuring it is valid and available on your system.
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `minchin.pelican.plugins.image_process`
DEBUG: Registering plugin `minchin.pelican.plugins.image_process`
DEBUG: Restoring system path
DEBUG: Template list: ['!simple/archives.html', '!simple/article.html', '!simple/author.html', '!simple/authors.html', '!simple/base.html', '!simple/categories.html', '!simple/category.html', '!simple/gosquared.html', '!simple/index.html', '!simple/page.html', '!simple/pagination.html', '!simple/period_archives.html', '!simple/tag.html', '!simple/tags.html', '!simple/translations.html', '!theme/analytics.html', '!theme/archives.html', '!theme/article.html', '!theme/article_infos.html', '!theme/author.html', '!theme/authors.html', '!theme/base.html', '!theme/category.html', '!theme/comments.html', '!theme/disqus_script.html', '!theme/github.html', '!theme/index.html', '!theme/page.html', '!theme/period_archives.html', '!theme/tag.html', '!theme/taglist.html', '!theme/tags.html', '!theme/translations.html', '!theme/twitter.html', 'analytics.html', 'archives.html', 'article.html', 'article_infos.html', 'author.html', 'authors.html', 'base.html', 'categories.html', 'category.html', 'comments.html', 'disqus_script.html', 'github.html', 'gosquared.html', 'index.html', 'page.html', 'pagination.html', 'period_archives.html', 'tag.html', 'taglist.html', 'tags.html', 'translations.html', 'twitter.html']
DEBUG: Read file posts/20190721-Lambda_pyodbc.md -> Article
DEBUG: Signal article_generator_preread.send(ArticlesGenerator)
DEBUG: Successfuly imported extension module "markdown.extensions.codehilite".
DEBUG: Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.extra".
DEBUG: Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
DEBUG: Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension".
DEBUG: Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension".
DEBUG: Successfully loaded extension "markdown.extensions.def_list.DefListExtension".
DEBUG: Successfully loaded extension "markdown.extensions.tables.TableExtension".
DEBUG: Successfully loaded extension "markdown.extensions.abbr.AbbrExtension".
DEBUG: Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.meta".
DEBUG: Successfully loaded extension "markdown.extensions.meta.MetaExtension".
DEBUG: Signal article_generator_context.send(ArticlesGenerator, <metadata>)
DEBUG: Read file pages/about.md -> Page
DEBUG: Signal page_generator_preread.send(PagesGenerator)
DEBUG: Signal page_generator_context.send(PagesGenerator, <metadata>)
DEBUG: Read file extra/CNAME -> Static
DEBUG: Signal static_generator_preread.send(StaticGenerator)
DEBUG: Signal static_generator_context.send(StaticGenerator, <metadata>)
-> Writing /home/nicko/projects/nicholasperkins.com/output/posts/using-pyodbc-in-aws-lambda-functions.html
CRITICAL: KeyError: 'filenames'
Traceback (most recent call last):
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/bin/pelican", line 10, in <module>
    sys.exit(main())
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/pelican/__init__.py", line 631, in main
    pelican.run()
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/pelican/__init__.py", line 198, in run
    p.generate_output(writer)
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/pelican/generators.py", line 689, in generate_output
    self.generate_pages(writer)
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/pelican/generators.py", line 598, in generate_pages
    self.generate_articles(write)
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/pelican/generators.py", line 470, in generate_articles
    url=article.url, blog=True)
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/pelican/writers.py", line 272, in write_file
    override_output)
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/pelican/writers.py", line 218, in _write_file
    signals.content_written.send(path, context=localcontext)
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/minchin/pelican/plugins/image_process.py", line 190, in harvest_images
    res = harvest_images_in_fragment(f, context)
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/minchin/pelican/plugins/image_process.py", line 230, in harvest_images_in_fragment
    build_srcset(img, settings, derivative)
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/minchin/pelican/plugins/image_process.py", line 289, in build_srcset
    path = compute_paths(img, settings, derivative)
  File "/home/nicko/.local/share/virtualenvs/nicholasperkins.com-BLbyW1XG/lib/python3.7/site-packages/minchin/pelican/plugins/image_process.py", line 252, in compute_paths
    for f, contobj in settings['filenames'].items():
KeyError: 'filenames'

**Comment by minchinweb** [comment]
Thanks for the report! I haven't looked at the code in a while, so it might make me a little bit to get it figured out...

**Comment by minchinweb** [comment]
@nickperkins I've released v1.2.0 which now supports Pelican version 4. Please let me know if you run into any further issues!
